// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarLfMVU0E_ePaLBwh-IFHNXZohI2H2Sg',
    appId: '1:949384960263:web:d6952580e270369791cda2',
    messagingSenderId: '949384960263',
    projectId: 'chat-app-84ae4',
    authDomain: 'chat-app-84ae4.firebaseapp.com',
    storageBucket: 'chat-app-84ae4.appspot.com',
    measurementId: 'G-8XMLRT34SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNUbaYFZiiEjqEhDZsudo9mbKPUkL5KPY',
    appId: '1:949384960263:android:9bc6ff351ab47bc691cda2',
    messagingSenderId: '949384960263',
    projectId: 'chat-app-84ae4',
    storageBucket: 'chat-app-84ae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4fqsmRVS9SqtsHh8qftQ2p-SCimf_N_s',
    appId: '1:949384960263:ios:7cf24a4a7c75c60091cda2',
    messagingSenderId: '949384960263',
    projectId: 'chat-app-84ae4',
    storageBucket: 'chat-app-84ae4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4fqsmRVS9SqtsHh8qftQ2p-SCimf_N_s',
    appId: '1:949384960263:ios:de62e90c807f81b091cda2',
    messagingSenderId: '949384960263',
    projectId: 'chat-app-84ae4',
    storageBucket: 'chat-app-84ae4.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
